/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: {
          50: 'var(--color-brand-soft-bg)',
          100: 'var(--color-brand-soft)',
          200: '#99F6E4',
          300: '#5EEAD4',
          400: '#2DD4BF',
          500: '#14B8A6',
          600: '#0D9488',
          700: '#0F766E',
          800: '#115E59',
          900: '#134E4A',
          950: '#042F2E',
        },
        accent: {
          50: 'var(--color-accent-soft)',
          100: '#FFEDD5',
          200: '#FED7AA',
          300: '#FDBA74',
          400: '#FB923C',
          500: '#F59E0B',
          600: '#D97706',
          700: '#B45309',
        },
        status: {
          approved: '#059669',
          approvedSoft: 'var(--color-status-approved-soft)',
          pending: '#D97706',
          pendingSoft: 'var(--color-status-pending-soft)',
          rejected: '#DC2626',
          rejectedSoft: 'var(--color-status-rejected-soft)',
          info: '#2563EB',
          infoSoft: 'var(--color-status-info-soft)',
          entry: '#059669',
          exit: '#DC2626',
        },
        surface: {
          DEFAULT: 'var(--color-surface)',
          card: 'var(--color-surface-card)',
          muted: 'var(--color-surface-muted)',
          border: 'var(--color-surface-border)',
        },
        ink: {
          DEFAULT: 'var(--color-ink)',
          soft: 'var(--color-ink-soft)',
          muted: 'var(--color-ink-muted)',
          faint: 'var(--color-ink-faint)',
        },
      },
      fontFamily: {
        display: ['Manrope_700Bold', 'Manrope_600SemiBold', 'System'],
        heading: ['Manrope_600SemiBold', 'System'],
        sans: ['Manrope_400Regular', 'System'],
        medium: ['Manrope_500Medium', 'System'],
      },
      boxShadow: {
        card: '0px 4px 16px rgba(15, 23, 42, 0.06)',
        soft: '0px 2px 8px rgba(15, 23, 42, 0.05)',
      },
    },
  },
  plugins: [],
};
