/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: {
          50: 'var(--color-brand-soft-bg)',
          100: 'var(--color-brand-soft)',
          200: '#FECDD3',
          300: '#FDA4AF',
          400: '#FB7185',
          500: '#F43F5E',
          600: '#E11D48',
          700: '#BE123C',
          800: '#9F1239',
          900: '#881337',
          950: '#4C0519',
        },
        accent: {
          50: 'var(--color-accent-soft)',
          100: '#E2E8F0',
          200: '#CBD5E1',
          300: '#94A3B8',
          400: '#64748B',
          500: '#334155',
          600: '#1E293B',
          700: '#0F172A',
        },
        charcoal: {
          DEFAULT: 'var(--color-charcoal)',
          soft: '#1E293B',
        },
        pastel: {
          mint: 'var(--color-pastel-mint)',
          peach: 'var(--color-pastel-peach)',
          sky: 'var(--color-pastel-sky)',
          rose: 'var(--color-pastel-rose)',
          butter: 'var(--color-pastel-butter)',
          lilac: 'var(--color-pastel-lilac)',
          sage: 'var(--color-pastel-sage)',
          coral: 'var(--color-pastel-coral)',
        },
        status: {
          approved: '#16A34A',
          approvedSoft: 'var(--color-status-approved-soft)',
          pending: '#F59E0B',
          pendingSoft: 'var(--color-status-pending-soft)',
          rejected: '#E11D48',
          rejectedSoft: 'var(--color-status-rejected-soft)',
          info: '#2563EB',
          infoSoft: 'var(--color-status-info-soft)',
          entry: '#16A34A',
          exit: '#E11D48',
        },
        surface: {
          DEFAULT: 'var(--color-surface)',
          card: 'var(--color-surface-card)',
          muted: 'var(--color-surface-muted)',
          border: 'var(--color-surface-border)',
        },
        ink: {
          DEFAULT: 'var(--color-ink)',
          soft: 'var(--color-ink-soft)',
          muted: 'var(--color-ink-muted)',
          faint: 'var(--color-ink-faint)',
        },
      },
      fontFamily: {
        display: ['Inter_700Bold', 'System'],
        heading: ['Inter_600SemiBold', 'System'],
        sans: ['Inter_400Regular', 'System'],
        medium: ['Inter_500Medium', 'System'],
      },
      fontSize: {
        'ds-display': ['32px', { lineHeight: '40px', letterSpacing: '-0.5px' }],
        'ds-heading': ['24px', { lineHeight: '32px', letterSpacing: '-0.3px' }],
        'ds-body': ['16px', { lineHeight: '24px' }],
        'ds-caption': ['13px', { lineHeight: '18px' }],
      },
      borderRadius: {
        card: '20px',
        panel: '20px',
        hero: '24px',
        modal: '28px',
        soft: '16px',
        bubbly: '20px',
        pill: '999px',
      },
      boxShadow: {
        'elevation-sm': '0px 2px 10px rgba(15, 23, 42, 0.06)',
        'elevation-md': '0px 6px 18px rgba(15, 23, 42, 0.08)',
        'elevation-lg': '0px 10px 28px rgba(15, 23, 42, 0.12)',
        card: '0px 2px 10px rgba(15, 23, 42, 0.06)',
        soft: '0px 6px 18px rgba(15, 23, 42, 0.08)',
      },
    },
  },
  plugins: [],
};
